version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-server
    ports:
      - "5677:80"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command: apache2-foreground
    restart: always
    networks:
      - app-network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-worker
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command: php scripts/worker.php
    depends_on:
      redis:
        condition: service_healthy
    restart: always
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis-server
    ports:
      - "127.0.0.1:6378:6379"
    volumes:
      - ./redis-data:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - app-network

networks:
  app-network:
    driver: bridge