services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-server
    ports:
      - "5677:80"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command: /bin/sh -c "composer install --no-interaction --prefer-dist --optimize-autoloader && composer update --no-interaction && apache2-foreground"
    restart: always

  redis:
    image: redis:7
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    restart: always
